#!/usr/bin/env python3
"""Generate scenes/dice-light-spot.json: three dice stacked/slanted in a
checkered room, lit by a spotlight aimed at the stack.

A die is a CSG chain: intersection(cube, sphere r=1.4) trims the corners,
then 21 pip spheres (hemispherical dimples, white material) are subtracted
one difference at a time. Materials sit on the CSG leaves — a material on a
CSG node would recolor the whole subtree, pips included.

Usage: python3 scenes/dice-light-spot.py [width height]   (default 3456 2234)
"""

import json
import math
import sys

PIP_R = 0.2
# Corner-trimming sphere. Edges sit at sqrt(2)~1.414 from the center, corners
# at sqrt(3)~1.732, so r=1.4 rounds the corners and just shaves the edges.
TRIM_R = 1.4

# Pip layouts per face value: (u, v) offsets in the face plane.
O = 0.5
LAYOUT = {
    1: [(0, 0)],
    2: [(-O, -O), (O, O)],
    3: [(-O, -O), (0, 0), (O, O)],
    4: [(-O, -O), (-O, O), (O, -O), (O, O)],
    5: [(-O, -O), (-O, O), (0, 0), (O, -O), (O, O)],
    6: [(-O, -O), (-O, 0), (-O, O), (O, -O), (O, 0), (O, O)],
}

# face -> (value, axis, sign); opposite faces sum to 7.
FACES = [
    (1, "y", +1), (6, "y", -1),
    (3, "x", +1), (4, "x", -1),
    (2, "z", +1), (5, "z", -1),
]

PIP_MATERIAL = {
    "color": [0.96, 0.94, 0.88],
    "diffuse": 0.8, "ambient": 0.15, "specular": 0.4, "shininess": 100,
}


def checkers(a):
    """The room's checkers pattern; `a` sets each surface's light-square tint."""
    return {
        "type": "checkers",
        "a": a, "b": [0.14, 0.13, 0.16],
        "transform": [{"scale": [2, 2, 2]}],
    }


def marble(a, b):
    """Bowling-ball swirl: perturbed stripes in one vibrant hue."""
    return {
        "type": "perturbed",
        "amplitude": 1.1,
        "frequency": 0.9,
        "seed": 11,
        "pattern": {
            "type": "stripe", "a": a, "b": b,
            "transform": [{"scale": [0.35, 0.35, 0.35]}, {"rotate_z": 0.9}],
        },
    }


def body_material(a, b):
    return {
        "pattern": marble(a, b),
        "diffuse": 0.75, "ambient": 0.2,
        "specular": 1.0, "shininess": 300, "reflective": 0.08,
    }


def pip(axis, sign, u, v):
    """A dimple sphere centered on the face at (u, v)."""
    center = {
        "x": [sign * 1.0, u, v],
        "y": [u, sign * 1.0, v],
        "z": [u, v, sign * 1.0],
    }[axis]
    return {
        "type": "sphere",
        "material": dict(PIP_MATERIAL),
        "transform": [{"scale": [PIP_R, PIP_R, PIP_R]}, {"translate": center}],
    }


def die(colors, transform):
    a, b = colors
    node = {
        "type": "csg", "operation": "intersection",
        "left": {"type": "cube", "material": body_material(a, b)},
        "right": {
            "type": "sphere", "material": body_material(a, b),
            "transform": [{"scale": [TRIM_R, TRIM_R, TRIM_R]}],
        },
    }
    for value, axis, sign in FACES:
        for u, v in LAYOUT[value]:
            node = {
                "type": "csg", "operation": "difference",
                "left": node,
                "right": pip(axis, sign, u, v),
            }
    node["transform"] = transform
    return node


def light():
    """Spotlight above-left of the camera, aimed at the stack: full intensity
    inside inner_angle, fading to nothing at outer_angle, so the dice sit in
    a pool of light and the room falls off to ambient."""
    return {
        "type": "spot",
        "position": [-3.0, 10.0, -4.0], "target": [0.1, 2.0, 0.3],
        "intensity": [1.2, 1.2, 1.2],
        "inner_angle": 0.22, "outer_angle": 0.42,
    }


def scene(width, height):
    magenta = ([0.93, 0.08, 0.45], [0.45, 0.02, 0.28])
    teal = ([0.0, 0.78, 0.82], [0.02, 0.32, 0.45])
    orange = ([1.0, 0.55, 0.05], [0.75, 0.18, 0.05])
    return {
        "comment": [
            "Three dice stacked in a checkered room; bowling-ball marble colors.",
            "Generated by scenes/dice-light-spot.py - edit that, not this.",
        ],
        "camera": {
            "width": width, "height": height, "field_of_view": 0.8,
            # 45 degrees onto the room's corner: equal x/z offset from `to`.
            "from": [-7.3, 4.8, -7.1], "to": [0.3, 1.6, 0.5], "up": [0, 1, 0],
            "antialias": {"n": 3},
        },
        "light": light(),
        "shapes": [
            {
                # back wall (z = 7), checkered in a pale mint tint
                "type": "plane",
                "material": {
                    "pattern": checkers([0.85, 0.93, 0.88]),
                    "diffuse": 0.8, "ambient": 0.15, "specular": 0.05,
                },
                "transform": [{"rotate_x": math.pi / 2},
                              {"translate": [0, 0, 7]}],
            },
            {
                # right wall (x = 7), a deeper mint so the corner reads
                "type": "plane",
                "material": {
                    "pattern": checkers([0.75, 0.93, 0.88]),
                    "diffuse": 0.8, "ambient": 0.15, "specular": 0.05,
                },
                "transform": [{"rotate_z": math.pi / 2},
                              {"translate": [7, 0, 0]}],
            },
            {
                # floor: warm cream checkers, glossy and slightly reflective
                "type": "plane",
                "material": {
                    "pattern": checkers([0.95, 0.93, 0.88]),
                    "diffuse": 0.8, "ambient": 0.2,
                    "specular": 0.3, "reflective": 0.12,
                },
            },
            die(magenta, [{"rotate_y": 0.3}, {"translate": [-1.15, 1.0, 0.0]}]),
            die(teal, [{"rotate_y": -0.5}, {"translate": [1.25, 1.0, 0.6]}]),
            die(orange, [{"rotate_y": math.pi / 4}, {"translate": [0.05, 3.0, 0.3]}]),
        ],
    }


def main():
    width, height = 3456, 2234
    if len(sys.argv) == 3:
        width, height = int(sys.argv[1]), int(sys.argv[2])
    out = "scenes/dice-light-spot.json"
    with open(out, "w") as f:
        json.dump(scene(width, height), f, indent=2)
        f.write("\n")
    print(f"wrote {out} ({width}x{height})")


if __name__ == "__main__":
    main()
