#!/usr/bin/env python3
"""Generate scenes/dice-light-spot.json: three dice stacked/slanted in a
checkered room, lit by a spotlight aimed at the stack, so the dice sit in a
pool of light and the room falls off to ambient. Builders in dicelib.py.

Usage: python3 scenes/dice-light-spot.py [width height]   (default 3456 2234)
"""

import math

import dicelib as dl


def scene(width, height):
    return {
        "comment": [
            "Three dice stacked in a checkered room; bowling-ball marble colors.",
            "Generated by scenes/dice-light-spot.py - edit that, not this.",
        ],
        # 45 degrees onto the room's corner: equal x/z offset from `to`.
        "camera": dl.camera(width, height, [-7.3, 4.8, -7.1], [0.3, 1.6, 0.5]),
        "light": dl.spot_light(),
        "shapes": dl.room() + [
            dl.die(dl.MAGENTA, [{"rotate_y": 0.3}, {"translate": [-1.15, 1.0, 0.0]}]),
            dl.die(dl.TEAL, [{"rotate_y": -0.5}, {"translate": [1.25, 1.0, 0.6]}]),
            dl.die(dl.ORANGE, [{"rotate_y": math.pi / 4}, {"translate": [0.05, 3.0, 0.3]}]),
        ],
    }


if __name__ == "__main__":
    dl.main("scenes/dice-light-spot.json", scene)
