#!/usr/bin/env python3
"""Generate scenes/dice-sentence.json: a sentence spelled out in small dice.

Each glyph is a 3x5 dot-matrix letter (dicelib.FONT) whose dots are dice,
standing upright on the checkered floor; colors cycle through the palette
per letter, and every die shows a random face with a little placement
jitter. The camera pulls back automatically to frame the text, and the
right-hand wall moves out of the way of long sentences. One group per
letter plus "bvh_threshold" keeps the render time sane.

Usage: python3 scenes/dice-sentence.py [TEXT] [width height]
       (defaults: "RTC", 3456 2234)
"""

import sys

import dicelib as dl

TEXT_Z = 3.0  # letters stand this far back; the wall behind them is at z=7


def scene(text, width, height):
    letters, text_w = dl.sentence_dice(text, z=TEXT_Z)
    # Frame the text: at fov 0.8 the visible half-width is dist*tan(0.4);
    # add margin and keep a sensible minimum for short words.
    distance = max(9.0, 1.45 * text_w)
    camera_from = [-0.05 * text_w, 4.6, TEXT_Z - distance]
    return {
        "comment": [
            f"'{text}' spelled in dice on a 3x5 dot-matrix grid.",
            "Generated by scenes/dice-sentence.py - edit that, not this.",
        ],
        "camera": dl.camera(width, height, camera_from, [0, 1.9, TEXT_Z]),
        "light": dl.area_light(),
        "settings": {"bvh_threshold": 4},
        "shapes": dl.room(right_x=max(7, text_w / 2 + 5)) + letters,
    }


def main():
    args = sys.argv[1:]
    text = args.pop(0) if args and not args[0].isdigit() else "RTC"
    width, height = (int(args[0]), int(args[1])) if len(args) == 2 else (3456, 2234)
    try:
        dl.write_scene(scene(text, width, height), "scenes/dice-sentence.json")
    except KeyError as e:
        sys.exit(f"dice-sentence: {e.args[0]}")


if __name__ == "__main__":
    main()
