//! Canvas
//!
//! This module defines what gets rendered to.
//!

// use crate::math::approx_eq;
use crate::tuple::Tuple;
use std::path::Path;

#[derive(Debug, Clone)]
pub struct Canvas {
    pub width: usize,
    pub height: usize,
    pixels: Vec<Tuple>,
}

impl Canvas {
    fn scale_color(v: f64) -> u8 {
        let v = v.clamp(0.0, 1.0);
        (v * 255.0 + 0.5) as u8
    }

    pub fn new(width: usize, height: usize) -> Self {
        let black = Tuple::color(0.0, 0.0, 0.0);
        Self {
            width,
            height,
            pixels: vec![black; width * height],
        }
    }

    pub fn height(&self) -> usize {
        self.height
    }

    pub fn width(&self) -> usize {
        self.width
    }

    /// Get the index of pixel at pos (x, y)
    ///
    /// # Examples
    /// ```
    /// # use rtc_rust::canvas::Canvas;
    ///
    /// let c = Canvas::new(10, 20);
    ///
    /// assert!(c.width == 10);
    /// assert!(c.height == 20);
    /// ```
    pub fn index(&self, x: usize, y: usize) -> usize {
        y * self.width + x
    }

    /// Get the color at a position
    ///
    /// # Examples
    /// ```
    /// # use rtc_rust::tuple::Tuple;
    /// # use rtc_rust::canvas::Canvas;
    ///
    /// let c = Canvas::new(10, 20);
    /// let black = Tuple::color(0.0, 0.0, 0.0);
    /// let color = c.pixel_at(0, 0);
    ///
    /// assert!(color.approx_eq(black));
    /// ```
    pub fn pixel_at(&self, x: usize, y: usize) -> Tuple {
        self.pixels[self.index(x, y)]
    }

    /// Write a color at a position
    ///
    /// # Examples
    /// ```
    /// # use rtc_rust::tuple::Tuple;
    /// # use rtc_rust::canvas::Canvas;
    ///
    /// let mut c = Canvas::new(10, 20);
    /// let white = Tuple::color(1.0, 1.0, 1.0);
    /// c[(0, 0)] = white;
    ///
    /// assert!(c[(0, 0)].approx_eq(white));
    /// ```
    pub fn write_pixel(&mut self, x: usize, y: usize, color: Tuple) {
        let idx = self.index(x, y);
        self.pixels[idx] = color;
    }

    pub fn to_ppm(&self) -> Vec<u8> {
        let mut data = Vec::new();

        data.extend_from_slice(b"P6\n");
        data.extend_from_slice(b"# Generated by rtc-rust\n");
        data.extend_from_slice(format!("{} {}\n", self.width, self.height).as_bytes());
        data.extend_from_slice(b"255\n");

        for y in 0..self.height {
            for x in 0..self.width {
                let c = self.pixel_at(x, y);

                let r = Self::scale_color(c.x);
                let g = Self::scale_color(c.y);
                let b = Self::scale_color(c.z);

                data.push(r);
                data.push(g);
                data.push(b);
            }
        }

        data
    }

    /// Convert canvas to PPM and write to disc.
    ///
    /// Internally calls Canvas::to_ppm().
    ///
    /// # Examples
    /// ```
    /// use rtc_rust::canvas::Canvas;
    /// let mut c = Canvas::new(10, 20);
    ///
    /// c.write_ppm("example.ppm").unwrap();
    ///
    /// ```
    pub fn write_ppm<P: AsRef<Path>>(&self, path: P) -> std::io::Result<()> {
        std::fs::write(path, self.to_ppm())
    }
}

use std::ops::{Index, IndexMut};

impl Index<(usize, usize)> for Canvas {
    type Output = Tuple;
    /// Implement indexing
    ///
    /// Allow index getter and setter. This allows
    /// array assignments and lookups like c\[(0,0)\].
    ///
    /// # Examples
    /// ```
    /// # use rtc_rust::canvas::Canvas;
    /// use rtc_rust::tuple::Tuple;
    /// let white = Tuple::color(1.0, 1.0, 1.0);
    /// let mut c = Canvas::new(10, 20);
    /// c[(0, 0)] = white;
    ///
    /// assert!(c.width() == 10);
    /// assert!(c.pixel_at(0,0) == white);
    /// assert!(c[(0, 0)] == white);
    /// ```
    fn index(&self, index: (usize, usize)) -> &Self::Output {
        let (x, y) = index;
        &self.pixels[self.index(x, y)]
    }
}

impl IndexMut<(usize, usize)> for Canvas {
    fn index_mut(&mut self, index: (usize, usize)) -> &mut Self::Output {
        let (x, y) = index;
        let idx = self.index(x, y);
        &mut self.pixels[idx]
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::light::Light;
    use crate::{logd, loge, logi, material::Material, matrix::Matrix4};

    /// Chap 2 - Creating a canvas
    #[test]
    fn test_chap_2_5() -> Result<(), String> {
        let c = Canvas::new(10, 20);
        let chk = c.width == 10 && c.height == 20;
        let black = Tuple::color(0.0, 0.0, 0.0);

        for pixel in &c.pixels {
            assert!(pixel.approx_eq(black));
        }

        for y in 0..c.height() {
            for x in 0..c.width() {
                assert!(c.pixel_at(x, y).approx_eq(black));
            }
        }

        if chk {
            Ok(())
        } else {
            logd!("test_chap_2_05", "w:{}", black.w);
            loge!("test_chap_2_05", "w:{}", black.w);
            logi!("test_chap_2_05", "w:{}", black.w);
            Err("Creating a canvas".into())
        }
    }

    /// Chap 2 -Writing pixels to a canvas
    #[test]
    fn test_chap_2_6() -> Result<(), String> {
        let mut c = Canvas::new(10, 20);
        let red = Tuple::color(1.0, 0.0, 0.0);
        c.write_pixel(2, 3, red);

        let chk = c.width == 10 && c.height == 20;
        let chk = chk && c[(2, 3)].approx_eq(red);

        if chk {
            Ok(())
        } else {
            Err("Writing pixels to a canvas".into())
        }
    }

    /// Chap 2 -Constructing the PPM header
    #[test]
    fn test_chap_2_7() -> std::io::Result<()> {
        let mut c = Canvas::new(5, 3);
        let red = Tuple::color(1.0, 0.0, 0.0);

        for y in 0..c.height() {
            for x in 0..c.width() {
                c.write_pixel(x, y, red);
            }
        }

        c.write_ppm("image_2_7.ppm")?;
        Ok(())
    }

    /// Chap 2 - Constructing the PPM pixel data
    #[test]
    fn test_chap_2_8() -> std::io::Result<()> {
        let mut c = Canvas::new(5, 3);
        let c1 = Tuple::color(1.5, 0.0, 0.0);
        let c2 = Tuple::color(0.0, 0.5, 0.0);
        let c3 = Tuple::color(-0.5, 0.0, 1.0);
        c.write_pixel(0, 0, c1);
        c.write_pixel(2, 1, c2);
        c.write_pixel(4, 2, c3);
        c.write_ppm("image_2_8.ppm")?;
        Ok(())
    }

    /// Chap 2 - Splitting long lines in PPM files
    /// NOTE: The actual splitting is not needed when using binary ppm.
    #[test]
    fn test_chap_2_9() -> std::io::Result<()> {
        let mut c = Canvas::new(1000, 200);
        let h = c.height();
        let w = c.width();
        for y in 0..h {
            for x in 0..w {
                let red = (x % 255) as f64 / 255.0;
                let green = (y % 255) as f64 / 255.0;
                let blue = red * green;
                c.write_pixel(x, y, Tuple::color(red, green, blue));
            }
        }
        c.write_ppm("image_2_9.ppm")?;
        Ok(())
    }

    #[derive(Debug, Copy, Clone, PartialEq)]
    pub struct Projectile {
        pub position: Tuple,
        pub velocity: Tuple,
    }

    impl Projectile {
        pub fn new(position: Tuple, velocity: Tuple) -> Self {
            Self { position, velocity }
        }

        pub fn tick(self, env: Environment) -> Projectile {
            Self {
                position: self.position + self.velocity,
                velocity: self.velocity + env.gravity + env.wind,
            }
        }
    }

    #[derive(Debug, Copy, Clone, PartialEq)]
    pub struct Environment {
        pub gravity: Tuple,
        pub wind: Tuple,
    }

    impl Environment {
        pub fn new(gravity: Tuple, wind: Tuple) -> Self {
            Self { gravity, wind }
        }
    }

    /// Chap 2 - Putting It Together
    #[test]
    #[ignore]
    fn test_chap_2_10() -> std::io::Result<()> {
        let start = Tuple::point(0.0, 1.0, 0.0);
        let velocity = Tuple::vector(1.0, 1.8, 0.0).normalize() * 11.25;

        let gravity = Tuple::vector(0.0, -0.1, 0.0);
        let wind = Tuple::vector(-0.01, 0.0, 0.0);
        let e = Environment::new(gravity, wind);

        let mut p = Projectile::new(start, velocity).tick(e);
        let mut c = Canvas::new(900, 550);

        // logi!("projectile", "y:{}", p.position.y);

        let width = c.width() as f64;
        let height = c.height() as f64;

        while p.position.y > 0.0 {
            // logi!("projectile", "y:{}", p.position.y);
            p = p.tick(e);
            let draw_y = height - p.position.y;

            if p.position.x < width && draw_y < height {
                c.write_pixel(
                    p.position.x as usize,
                    draw_y as usize,
                    Tuple::color(1.0, 0.0, 0.0),
                );
            }
        }

        c.write_ppm("image_2_10.ppm")?;
        Ok(())
    }

    /// Chap 5 - Putting it Together
    #[test]
    fn test_chap_5_20() -> std::io::Result<()> {
        use crate::ray::Ray;
        use crate::shape::Shape;
        use crate::shapes::sphere::Sphere;
        use crate::tuple::Tuple;
        let ray_origin = Tuple::point(0.0, 0.0, -5.0);
        let wall_z = 10.0;
        let wall_size = 7.0;
        let canvas_pixels = 100;
        let pixel_size = wall_size / canvas_pixels as f64;
        let half = wall_size / 2.0;
        let mut s = Sphere::new();
        // s.set_transform(Matrix4::scaling(1.0, 0.5, 1.0));
        // s.set_transform(Matrix4::scaling(0.5, 1.0, 1.0));
        // s.set_transform(
        //     Matrix4::rotation_z(std::f64::consts::PI / 4.0) * Matrix4::scaling(0.5, 1.0, 1.0),
        // );
        s.set_transform(
            Matrix4::shearing(1.0, 0.0, 0.0, 0.0, 0.0, 0.0) * Matrix4::scaling(0.5, 1.0, 1.0),
        );

        let mut c = Canvas::new(canvas_pixels, canvas_pixels);

        let h = c.height();
        let w = c.width();
        for y in 0..h {
            let world_y = half - pixel_size * y as f64;
            for x in 0..w {
                let world_x = -half + pixel_size * x as f64;
                let position = Tuple::point(world_x, world_y, wall_z);
                let r = Ray::new(ray_origin, (position - ray_origin).normalize());
                let xs = s.intersect(&r);
                if !xs.is_empty() {
                    let color = Tuple::color(1.0, y as f64 / h as f64, x as f64 / w as f64);
                    c.write_pixel(x, y, color);
                }
            }
        }

        c.write_ppm("image_5_20.ppm")?;
        Ok(())
    }

    /// Chap 6 - Putting it Together
    #[test]
    fn test_chap_6_18() -> std::io::Result<()> {
        use crate::ray::Ray;
        use crate::shape::Shape;
        use crate::shapes::sphere::Sphere;
        use crate::tuple::Tuple;
        let ray_origin = Tuple::point(0.0, 0.0, -5.0);
        let wall_z = 10.0;
        let wall_size = 7.0;
        let canvas_pixels = 100;
        let pixel_size = wall_size / canvas_pixels as f64;
        let half = wall_size / 2.0;
        let mut s = Sphere::new();
        s.set_transform(Matrix4::scaling(1.0, 0.5, 1.0));
        s.set_transform(Matrix4::scaling(0.5, 1.0, 1.0));
        s.set_transform(
            Matrix4::rotation_z(std::f64::consts::PI / 4.0) * Matrix4::scaling(0.5, 1.0, 1.0),
        );
        s.set_transform(
            Matrix4::shearing(1.0, 0.0, 0.0, 0.0, 0.0, 0.0) * Matrix4::scaling(0.5, 1.0, 1.0),
        );

        let mut m = Material::new();
        m.color = Tuple::color(1.0, 0.2, 1.0);

        s.set_material(m.clone());

        let light_position = Tuple::point(-10.0, 10.0, -10.0);
        let light_color = Tuple::color(1.0, 1.0, 1.0);
        let light = Light::point_light(light_position, light_color);
        let mut c = Canvas::new(canvas_pixels, canvas_pixels);

        let h = c.height();
        let w = c.width();
        for y in 0..h {
            let world_y = half - pixel_size * y as f64;
            for x in 0..w {
                let world_x = -half + pixel_size * x as f64;
                let position = Tuple::point(world_x, world_y, wall_z);
                let r = Ray::new(ray_origin, (position - ray_origin).normalize());
                let xs = s.intersect(&r);
                if !xs.is_empty() {
                    let hit = xs[0];
                    let point = r.position(hit.t);
                    let normalv = s.normal_at(point);
                    let eyev = -r.direction;
                    let in_shadow = false;
                    // let color = light.lighting(&m, point, eyev, normalv, in_shadow);
                    let color = light.lighting(&s, point, point, eyev, normalv, in_shadow);
                    c.write_pixel(x, y, color);
                }
            }
        }

        c.write_ppm("image_6_18.ppm")?;
        Ok(())
    }
}
