//! Canvas
//!
//! This module defines what gets rendered to.
//!

// use crate::math::approx_eq;
use crate::tuple::Tuple;
use std::path::Path;

#[derive(Debug, Clone)]
pub struct Canvas {
    pub width: usize,
    pub height: usize,
    pixels: Vec<Tuple>,
}

impl Canvas {
    fn scale_color(v: f64) -> u8 {
        let v = v.clamp(0.0, 1.0);
        (v * 255.0 + 0.5) as u8
    }

    pub fn new(width: usize, height: usize) -> Self {
        let black = Tuple::color(0.0, 0.0, 0.0);
        Self {
            width,
            height,
            pixels: vec![black; width * height],
        }
    }

    pub fn height(&self) -> usize {
        self.height
    }

    pub fn width(&self) -> usize {
        self.width
    }

    /// Get the index of pixel at pos (x, y)
    ///
    /// # Examples
    /// ```
    /// # use rtc_rust::canvas::Canvas;
    ///
    /// let c = Canvas::new(10, 20);
    ///
    /// assert!(c.width == 10);
    /// assert!(c.height == 20);
    /// ```
    pub fn index(&self, x: usize, y: usize) -> usize {
        y * self.width + x
    }

    /// Get the color at a position
    ///
    /// # Examples
    /// ```
    /// # use rtc_rust::tuple::Tuple;
    /// # use rtc_rust::canvas::Canvas;
    ///
    /// let c = Canvas::new(10, 20);
    /// let black = Tuple::color(0.0, 0.0, 0.0);
    /// let color = c.pixel_at(0, 0);
    ///
    /// assert!(color.approx_eq(black));
    /// ```
    pub fn pixel_at(&self, x: usize, y: usize) -> Tuple {
        self.pixels[self.index(x, y)]
    }

    /// Write a color at a position
    ///
    /// # Examples
    /// ```
    /// # use rtc_rust::tuple::Tuple;
    /// # use rtc_rust::canvas::Canvas;
    ///
    /// let mut c = Canvas::new(10, 20);
    /// let white = Tuple::color(1.0, 1.0, 1.0);
    /// c[(0, 0)] = white;
    ///
    /// assert!(c[(0, 0)].approx_eq(white));
    /// ```
    pub fn write_pixel(&mut self, x: usize, y: usize, color: Tuple) {
        let idx = self.index(x, y);
        self.pixels[idx] = color;
    }

    pub fn to_ppm(&self) -> Vec<u8> {
        let mut data = Vec::new();

        data.extend_from_slice(b"P6\n");
        data.extend_from_slice(b"# Generated by rtc-rust\n");
        data.extend_from_slice(format!("{} {}\n", self.width, self.height).as_bytes());
        data.extend_from_slice(b"255\n");

        for y in 0..self.height {
            for x in 0..self.width {
                let c = self.pixel_at(x, y);

                let r = Self::scale_color(c.x);
                let g = Self::scale_color(c.y);
                let b = Self::scale_color(c.z);

                data.push(r);
                data.push(g);
                data.push(b);
            }
        }

        data
    }

    /// Convert canvas to PPM and write to disc.
    ///
    /// Internally calls Canvas::to_ppm().
    ///
    /// # Examples
    /// ```
    /// use rtc_rust::canvas::Canvas;
    /// let mut c = Canvas::new(10, 20);
    ///
    /// c.write_ppm("example.ppm").unwrap();
    ///
    /// ```
    pub fn write_ppm<P: AsRef<Path>>(&self, path: P) -> std::io::Result<()> {
        std::fs::write(path, self.to_ppm())
    }

    /// Parse an ASCII PPM (`P3`). Comments (`#` to end of line) are
    /// ignored anywhere; RGB triples may span lines; samples are scaled by
    /// the header's maximum value.
    ///
    /// # Examples
    /// ```
    /// use rtc_rust::canvas::Canvas;
    /// use rtc_rust::tuple::Tuple;
    /// let c = Canvas::from_ppm("P3\n1 1\n255\n51 153 204\n").unwrap();
    /// assert!(c.pixel_at(0, 0).approx_eq(Tuple::color(0.2, 0.6, 0.8)));
    /// ```
    pub fn from_ppm(ppm: &str) -> Result<Self, String> {
        let mut tokens = ppm
            .lines()
            .map(|line| line.split('#').next().unwrap_or(""))
            .flat_map(|line| line.split_whitespace())
            .map(str::to_string);

        let mut next = |what: &str| {
            tokens
                .next()
                .ok_or_else(|| format!("PPM: unexpected end of data reading {what}"))
        };
        let magic = next("magic number")?;
        if magic != "P3" {
            return Err(format!("PPM: expected magic number P3, got {magic}"));
        }
        let parse = |s: String, what: &str| {
            s.parse::<f64>()
                .map_err(|e| format!("PPM: bad {what} '{s}': {e}"))
        };
        let width = parse(next("width")?, "width")? as usize;
        let height = parse(next("height")?, "height")? as usize;
        let scale = parse(next("scale")?, "scale")?;

        let mut canvas = Canvas::new(width, height);
        for y in 0..height {
            for x in 0..width {
                let r = parse(next("red sample")?, "sample")? / scale;
                let g = parse(next("green sample")?, "sample")? / scale;
                let b = parse(next("blue sample")?, "sample")? / scale;
                canvas.write_pixel(x, y, Tuple::color(r, g, b));
            }
        }
        Ok(canvas)
    }

    /// Parse a binary PPM (`P6`, 8-bit samples) — the format `to_ppm`
    /// writes, so a render can be used as a texture.
    pub fn from_ppm_binary(data: &[u8]) -> Result<Self, String> {
        // Header: magic, width, height, maxval as whitespace-separated
        // tokens (comments allowed), then a single whitespace byte, then
        // width*height*3 raw samples.
        let mut pos = 0;
        let mut header: Vec<String> = Vec::new();
        while header.len() < 4 {
            while pos < data.len() && data[pos].is_ascii_whitespace() {
                pos += 1;
            }
            if pos < data.len() && data[pos] == b'#' {
                while pos < data.len() && data[pos] != b'\n' {
                    pos += 1;
                }
                continue;
            }
            let start = pos;
            while pos < data.len() && !data[pos].is_ascii_whitespace() {
                pos += 1;
            }
            if start == pos {
                return Err("PPM: unexpected end of header".into());
            }
            header.push(String::from_utf8_lossy(&data[start..pos]).into_owned());
        }
        pos += 1; // the single whitespace byte after maxval

        if header[0] != "P6" {
            return Err(format!("PPM: expected magic number P6, got {}", header[0]));
        }
        let dim = |s: &str| {
            s.parse::<usize>()
                .map_err(|e| format!("PPM: bad '{s}': {e}"))
        };
        let (width, height, maxval) = (dim(&header[1])?, dim(&header[2])?, dim(&header[3])?);
        if maxval > 255 {
            return Err("PPM: only 8-bit P6 is supported".into());
        }
        let samples = &data[pos..];
        if samples.len() < width * height * 3 {
            return Err("PPM: not enough pixel data".into());
        }

        let scale = maxval as f64;
        let mut canvas = Canvas::new(width, height);
        for (i, px) in samples.chunks_exact(3).take(width * height).enumerate() {
            let color = Tuple::color(
                px[0] as f64 / scale,
                px[1] as f64 / scale,
                px[2] as f64 / scale,
            );
            canvas.write_pixel(i % width, i / width, color);
        }
        Ok(canvas)
    }

    /// Read a PPM file, dispatching on its magic number (`P3` or `P6`).
    pub fn read_ppm<P: AsRef<Path>>(path: P) -> Result<Self, String> {
        let data = std::fs::read(&path).map_err(|e| format!("{}: {e}", path.as_ref().display()))?;
        if data.starts_with(b"P6") {
            Self::from_ppm_binary(&data)
        } else {
            Self::from_ppm(&String::from_utf8_lossy(&data))
        }
    }
}

use std::ops::{Index, IndexMut};

impl Index<(usize, usize)> for Canvas {
    type Output = Tuple;
    /// Implement indexing
    ///
    /// Allow index getter and setter. This allows
    /// array assignments and lookups like c\[(0,0)\].
    ///
    /// # Examples
    /// ```
    /// # use rtc_rust::canvas::Canvas;
    /// use rtc_rust::tuple::Tuple;
    /// let white = Tuple::color(1.0, 1.0, 1.0);
    /// let mut c = Canvas::new(10, 20);
    /// c[(0, 0)] = white;
    ///
    /// assert!(c.width() == 10);
    /// assert!(c.pixel_at(0,0) == white);
    /// assert!(c[(0, 0)] == white);
    /// ```
    fn index(&self, index: (usize, usize)) -> &Self::Output {
        let (x, y) = index;
        &self.pixels[self.index(x, y)]
    }
}

impl IndexMut<(usize, usize)> for Canvas {
    fn index_mut(&mut self, index: (usize, usize)) -> &mut Self::Output {
        let (x, y) = index;
        let idx = self.index(x, y);
        &mut self.pixels[idx]
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::light::Light;
    use crate::{logd, loge, logi, material::Material, matrix::Matrix4};

    /// Chap 2 - Creating a canvas
    #[test]
    fn test_chap_2_5() -> Result<(), String> {
        let c = Canvas::new(10, 20);
        let chk = c.width == 10 && c.height == 20;
        let black = Tuple::color(0.0, 0.0, 0.0);

        for pixel in &c.pixels {
            assert!(pixel.approx_eq(black));
        }

        for y in 0..c.height() {
            for x in 0..c.width() {
                assert!(c.pixel_at(x, y).approx_eq(black));
            }
        }

        if chk {
            Ok(())
        } else {
            logd!("test_chap_2_05", "w:{}", black.w);
            loge!("test_chap_2_05", "w:{}", black.w);
            logi!("test_chap_2_05", "w:{}", black.w);
            Err("Creating a canvas".into())
        }
    }

    /// Chap 2 -Writing pixels to a canvas
    #[test]
    fn test_chap_2_6() -> Result<(), String> {
        let mut c = Canvas::new(10, 20);
        let red = Tuple::color(1.0, 0.0, 0.0);
        c.write_pixel(2, 3, red);

        let chk = c.width == 10 && c.height == 20;
        let chk = chk && c[(2, 3)].approx_eq(red);

        if chk {
            Ok(())
        } else {
            Err("Writing pixels to a canvas".into())
        }
    }

    /// Chap 2 -Constructing the PPM header
    #[test]
    fn test_chap_2_7() -> std::io::Result<()> {
        let mut c = Canvas::new(5, 3);
        let red = Tuple::color(1.0, 0.0, 0.0);

        for y in 0..c.height() {
            for x in 0..c.width() {
                c.write_pixel(x, y, red);
            }
        }

        c.write_ppm("image_2_7.ppm")?;
        Ok(())
    }

    /// Chap 2 - Constructing the PPM pixel data
    #[test]
    fn test_chap_2_8() -> std::io::Result<()> {
        let mut c = Canvas::new(5, 3);
        let c1 = Tuple::color(1.5, 0.0, 0.0);
        let c2 = Tuple::color(0.0, 0.5, 0.0);
        let c3 = Tuple::color(-0.5, 0.0, 1.0);
        c.write_pixel(0, 0, c1);
        c.write_pixel(2, 1, c2);
        c.write_pixel(4, 2, c3);
        c.write_ppm("image_2_8.ppm")?;
        Ok(())
    }

    /// Chap 2 - Splitting long lines in PPM files
    /// NOTE: The actual splitting is not needed when using binary ppm.
    #[test]
    fn test_chap_2_9() -> std::io::Result<()> {
        let mut c = Canvas::new(1000, 200);
        let h = c.height();
        let w = c.width();
        for y in 0..h {
            for x in 0..w {
                let red = (x % 255) as f64 / 255.0;
                let green = (y % 255) as f64 / 255.0;
                let blue = red * green;
                c.write_pixel(x, y, Tuple::color(red, green, blue));
            }
        }
        c.write_ppm("image_2_9.ppm")?;
        Ok(())
    }

    #[derive(Debug, Copy, Clone, PartialEq)]
    pub struct Projectile {
        pub position: Tuple,
        pub velocity: Tuple,
    }

    impl Projectile {
        pub fn new(position: Tuple, velocity: Tuple) -> Self {
            Self { position, velocity }
        }

        pub fn tick(self, env: Environment) -> Projectile {
            Self {
                position: self.position + self.velocity,
                velocity: self.velocity + env.gravity + env.wind,
            }
        }
    }

    #[derive(Debug, Copy, Clone, PartialEq)]
    pub struct Environment {
        pub gravity: Tuple,
        pub wind: Tuple,
    }

    impl Environment {
        pub fn new(gravity: Tuple, wind: Tuple) -> Self {
            Self { gravity, wind }
        }
    }

    /// Chap 2 - Putting It Together
    #[test]
    #[ignore]
    fn test_chap_2_10() -> std::io::Result<()> {
        let start = Tuple::point(0.0, 1.0, 0.0);
        let velocity = Tuple::vector(1.0, 1.8, 0.0).normalize() * 11.25;

        let gravity = Tuple::vector(0.0, -0.1, 0.0);
        let wind = Tuple::vector(-0.01, 0.0, 0.0);
        let e = Environment::new(gravity, wind);

        let mut p = Projectile::new(start, velocity).tick(e);
        let mut c = Canvas::new(900, 550);

        // logi!("projectile", "y:{}", p.position.y);

        let width = c.width() as f64;
        let height = c.height() as f64;

        while p.position.y > 0.0 {
            // logi!("projectile", "y:{}", p.position.y);
            p = p.tick(e);
            let draw_y = height - p.position.y;

            if p.position.x < width && draw_y < height {
                c.write_pixel(
                    p.position.x as usize,
                    draw_y as usize,
                    Tuple::color(1.0, 0.0, 0.0),
                );
            }
        }

        c.write_ppm("image_2_10.ppm")?;
        Ok(())
    }

    /// Chap 5 - Putting it Together
    #[test]
    fn test_chap_5_20() -> std::io::Result<()> {
        use crate::ray::Ray;
        use crate::shape::Shape;
        use crate::shapes::sphere::Sphere;
        use crate::tuple::Tuple;
        let ray_origin = Tuple::point(0.0, 0.0, -5.0);
        let wall_z = 10.0;
        let wall_size = 7.0;
        let canvas_pixels = 100;
        let pixel_size = wall_size / canvas_pixels as f64;
        let half = wall_size / 2.0;
        let mut s = Sphere::new();
        // s.set_transform(Matrix4::scaling(1.0, 0.5, 1.0));
        // s.set_transform(Matrix4::scaling(0.5, 1.0, 1.0));
        // s.set_transform(
        //     Matrix4::rotation_z(std::f64::consts::PI / 4.0) * Matrix4::scaling(0.5, 1.0, 1.0),
        // );
        s.set_transform(
            Matrix4::shearing(1.0, 0.0, 0.0, 0.0, 0.0, 0.0) * Matrix4::scaling(0.5, 1.0, 1.0),
        );

        let mut c = Canvas::new(canvas_pixels, canvas_pixels);

        let h = c.height();
        let w = c.width();
        for y in 0..h {
            let world_y = half - pixel_size * y as f64;
            for x in 0..w {
                let world_x = -half + pixel_size * x as f64;
                let position = Tuple::point(world_x, world_y, wall_z);
                let r = Ray::new(ray_origin, (position - ray_origin).normalize());
                let xs = s.intersect(&r);
                if !xs.is_empty() {
                    let color = Tuple::color(1.0, y as f64 / h as f64, x as f64 / w as f64);
                    c.write_pixel(x, y, color);
                }
            }
        }

        c.write_ppm("image_5_20.ppm")?;
        Ok(())
    }

    /// Chap 6 - Putting it Together
    #[test]
    fn test_chap_6_18() -> std::io::Result<()> {
        use crate::ray::Ray;
        use crate::shape::Shape;
        use crate::shapes::sphere::Sphere;
        use crate::tuple::Tuple;
        let ray_origin = Tuple::point(0.0, 0.0, -5.0);
        let wall_z = 10.0;
        let wall_size = 7.0;
        let canvas_pixels = 100;
        let pixel_size = wall_size / canvas_pixels as f64;
        let half = wall_size / 2.0;
        let mut s = Sphere::new();
        s.set_transform(Matrix4::scaling(1.0, 0.5, 1.0));
        s.set_transform(Matrix4::scaling(0.5, 1.0, 1.0));
        s.set_transform(
            Matrix4::rotation_z(std::f64::consts::PI / 4.0) * Matrix4::scaling(0.5, 1.0, 1.0),
        );
        s.set_transform(
            Matrix4::shearing(1.0, 0.0, 0.0, 0.0, 0.0, 0.0) * Matrix4::scaling(0.5, 1.0, 1.0),
        );

        let mut m = Material::new();
        m.color = Tuple::color(1.0, 0.2, 1.0);

        s.set_material(m.clone());

        let light_position = Tuple::point(-10.0, 10.0, -10.0);
        let light_color = Tuple::color(1.0, 1.0, 1.0);
        let light = Light::point_light(light_position, light_color);
        let mut c = Canvas::new(canvas_pixels, canvas_pixels);

        let h = c.height();
        let w = c.width();
        for y in 0..h {
            let world_y = half - pixel_size * y as f64;
            for x in 0..w {
                let world_x = -half + pixel_size * x as f64;
                let position = Tuple::point(world_x, world_y, wall_z);
                let r = Ray::new(ray_origin, (position - ray_origin).normalize());
                let xs = s.intersect(&r);
                if !xs.is_empty() {
                    let hit = xs[0];
                    let point = r.position(hit.t);
                    let normalv = s.normal_at_no_intersect(point);
                    let eyev = -r.direction;
                    let intensity = 1.0;
                    // let color = light.lighting(&m, point, eyev, normalv, in_shadow);
                    let color = light.lighting(&s, point, point, eyev, normalv, intensity);
                    c.write_pixel(x, y, color);
                }
            }
        }

        c.write_ppm("image_6_18.ppm")?;
        Ok(())
    }

    /// Bonus (texture mapping) - Reading a file with the wrong magic number
    #[test]
    fn test_bonus_texture_18() -> Result<(), String> {
        let ppm = "P32\n1 1\n255\n0 0 0\n";
        match Canvas::from_ppm(ppm) {
            Err(_) => Ok(()),
            Ok(_) => Err("Reading a file with the wrong magic number should fail".into()),
        }
    }

    /// Bonus (texture mapping) - Reading a PPM returns a canvas of the right size
    #[test]
    fn test_bonus_texture_19() -> Result<(), String> {
        let ppm = "P3\n10 2\n255\n\
            0 0 0  0 0 0  0 0 0  0 0 0  0 0 0  0 0 0  0 0 0  0 0 0  0 0 0  0 0 0\n\
            0 0 0  0 0 0  0 0 0  0 0 0  0 0 0  0 0 0  0 0 0  0 0 0  0 0 0  0 0 0\n";
        let c = Canvas::from_ppm(ppm)?;
        if c.width() == 10 && c.height() == 2 {
            Ok(())
        } else {
            Err("Reading a PPM returns a canvas of the right size".into())
        }
    }

    /// Bonus (texture mapping) - Reading pixel data from a PPM file
    #[test]
    fn test_bonus_texture_21() -> Result<(), String> {
        let ppm = "P3\n4 3\n255\n\
            255 127 0  0 127 255  127 255 0  255 255 255\n\
            0 0 0  255 0 0  0 255 0  0 0 255\n\
            255 255 0  0 255 255  255 0 255  127 127 127\n";
        let c = Canvas::from_ppm(ppm)?;
        let g = 127.0 / 255.0;
        let cases = [
            (0, 0, Tuple::color(1.0, g, 0.0)),
            (1, 0, Tuple::color(0.0, g, 1.0)),
            (2, 0, Tuple::color(g, 1.0, 0.0)),
            (3, 0, Tuple::color(1.0, 1.0, 1.0)),
            (0, 1, Tuple::color(0.0, 0.0, 0.0)),
            (1, 1, Tuple::color(1.0, 0.0, 0.0)),
            (2, 1, Tuple::color(0.0, 1.0, 0.0)),
            (3, 1, Tuple::color(0.0, 0.0, 1.0)),
            (0, 2, Tuple::color(1.0, 1.0, 0.0)),
            (1, 2, Tuple::color(0.0, 1.0, 1.0)),
            (2, 2, Tuple::color(1.0, 0.0, 1.0)),
            (3, 2, Tuple::color(g, g, g)),
        ];
        for (x, y, expected) in cases {
            if !c.pixel_at(x, y).approx_eq(expected) {
                loge!(
                    "test_bonus_texture_21",
                    "({x},{y}) got:{}",
                    c.pixel_at(x, y)
                );
                return Err("Reading pixel data from a PPM file".into());
            }
        }
        Ok(())
    }

    /// Bonus (texture mapping) - PPM parsing ignores comment lines
    #[test]
    fn test_bonus_texture_22() -> Result<(), String> {
        let ppm = "P3\n# this is a comment\n2 1\n# this, too\n255\n# another comment\n\
            255 255 255\n# oh, no, comments in the pixel data!\n255 0 255\n";
        let c = Canvas::from_ppm(ppm)?;
        let chk = c.pixel_at(0, 0).approx_eq(Tuple::color(1.0, 1.0, 1.0))
            && c.pixel_at(1, 0).approx_eq(Tuple::color(1.0, 0.0, 1.0));
        if chk {
            Ok(())
        } else {
            Err("PPM parsing ignores comment lines".into())
        }
    }

    /// Bonus (texture mapping) - PPM parsing allows an RGB triple to span lines
    #[test]
    fn test_bonus_texture_23() -> Result<(), String> {
        let ppm = "P3\n1 1\n255\n51\n153\n\n204\n";
        let c = Canvas::from_ppm(ppm)?;
        if c.pixel_at(0, 0).approx_eq(Tuple::color(0.2, 0.6, 0.8)) {
            Ok(())
        } else {
            Err("PPM parsing allows an RGB triple to span lines".into())
        }
    }

    /// Bonus (texture mapping) - PPM parsing respects the scale setting
    #[test]
    fn test_bonus_texture_24() -> Result<(), String> {
        let ppm = "P3\n2 2\n100\n100 100 100  50 50 50\n75 50 25  0 0 0\n";
        let c = Canvas::from_ppm(ppm)?;
        if c.pixel_at(0, 1).approx_eq(Tuple::color(0.75, 0.5, 0.25)) {
            Ok(())
        } else {
            Err("PPM parsing respects the scale setting".into())
        }
    }

    /// Binary PPM (P6) round trip: what `to_ppm` writes, `from_ppm_binary`
    /// reads back (to 8-bit precision)
    #[test]
    fn test_bonus_texture_25() -> Result<(), String> {
        let mut c = Canvas::new(3, 2);
        c.write_pixel(0, 0, Tuple::color(1.0, 0.5, 0.0));
        c.write_pixel(2, 1, Tuple::color(0.2, 0.6, 0.8));
        let back = Canvas::from_ppm_binary(&c.to_ppm())?;
        let close = |a: Tuple, b: Tuple| {
            (a.x - b.x).abs() < 1.0 / 255.0
                && (a.y - b.y).abs() < 1.0 / 255.0
                && (a.z - b.z).abs() < 1.0 / 255.0
        };
        let chk = back.width() == 3
            && back.height() == 2
            && close(back.pixel_at(0, 0), c.pixel_at(0, 0))
            && close(back.pixel_at(2, 1), c.pixel_at(2, 1))
            && close(back.pixel_at(1, 0), Tuple::color(0.0, 0.0, 0.0));
        if chk {
            Ok(())
        } else {
            Err("Binary PPM round trip".into())
        }
    }
}
