#!/usr/bin/env python3
# Generate the OBJ models committed in this directory.
#
# Copyright (c) 2026 Willy Clarke
# MIT License (see LICENSE at the repository root).
#
# The models are deliberately simple: they only need to demonstrate that
# the OBJ parser and the triangle shapes in this crate work.
#
#   icosahedron.obj  - 12 vertices / 20 faces, no normals -> flat shading
#   torus_smooth.obj - torus with analytic vertex normals -> smooth shading
#
# Run from this directory: python3 generate.py

import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))

HEADER = """# {name}
# Generated by generate.py in this directory - do not edit by hand.
# Copyright (c) 2026 Willy Clarke, MIT License (see LICENSE at repo root).
"""


def write_icosahedron(path):
    """Regular icosahedron, circumradius 1, centered on the origin."""
    phi = (1.0 + math.sqrt(5.0)) / 2.0
    raw = [
        (-1, phi, 0), (1, phi, 0), (-1, -phi, 0), (1, -phi, 0),
        (0, -1, phi), (0, 1, phi), (0, -1, -phi), (0, 1, -phi),
        (phi, 0, -1), (phi, 0, 1), (-phi, 0, -1), (-phi, 0, 1),
    ]
    scale = 1.0 / math.sqrt(1.0 + phi * phi)  # circumradius -> 1
    verts = [(x * scale, y * scale, z * scale) for (x, y, z) in raw]
    faces = [  # 0-based, outward winding
        (0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
        (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
        (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
        (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1),
    ]
    with open(path, "w") as f:
        f.write(HEADER.format(name="Regular icosahedron, circumradius 1"))
        for v in verts:
            f.write("v {:.6f} {:.6f} {:.6f}\n".format(*v))
        for a, b, c in faces:
            f.write(f"f {a + 1} {b + 1} {c + 1}\n")
    print(f"wrote {path}: {len(verts)} vertices, {len(faces)} faces")


def write_torus(path, major=1.0, minor=0.4, n_major=32, n_minor=16):
    """Torus in the xz plane (y up) with exact analytic vertex normals."""
    verts = []
    norms = []
    for i in range(n_major):
        theta = 2.0 * math.pi * i / n_major
        ct, st = math.cos(theta), math.sin(theta)
        for j in range(n_minor):
            phi = 2.0 * math.pi * j / n_minor
            cp, sp = math.cos(phi), math.sin(phi)
            # unit normal points from the tube's center circle to the surface
            norms.append((ct * cp, sp, st * cp))
            verts.append((ct * (major + minor * cp), minor * sp, st * (major + minor * cp)))

    def vid(i, j):  # 0-based index with wraparound
        return (i % n_major) * n_minor + (j % n_minor)

    faces = []
    for i in range(n_major):
        for j in range(n_minor):
            a, b = vid(i, j), vid(i + 1, j)
            c, d = vid(i + 1, j + 1), vid(i, j + 1)
            faces.append((a, b, c))
            faces.append((a, c, d))

    with open(path, "w") as f:
        f.write(HEADER.format(
            name=f"Torus, major radius {major}, minor radius {minor}, "
                 f"{n_major}x{n_minor} segments, analytic vertex normals"))
        for v in verts:
            f.write("v {:.6f} {:.6f} {:.6f}\n".format(*v))
        for n in norms:
            f.write("vn {:.6f} {:.6f} {:.6f}\n".format(*n))
        for a, b, c in faces:
            f.write(f"f {a + 1}//{a + 1} {b + 1}//{b + 1} {c + 1}//{c + 1}\n")
    print(f"wrote {path}: {len(verts)} vertices, {len(faces)} faces")


if __name__ == "__main__":
    write_icosahedron(os.path.join(HERE, "icosahedron.obj"))
    write_torus(os.path.join(HERE, "torus_smooth.obj"))
